// <auto-generated />
namespace Technoloshe20173CSeriesMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CambioNombreFKGenreID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambioNombreFKGenreID));
        
        string IMigrationMetadata.Id
        {
            get { return "201712121710399_CambioNombreFKGenreID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
